#!/usr/bin/env php
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace MagentoDevBox;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/Command/Wrapper/MagentoInstallAll.php';

use MagentoDevBox\Command\Wrapper\MagentoInstallAll;
use Symfony\Component\Console\Application;

$application = new Application();
$commands = [];

foreach (glob(__DIR__ . '/Command/*.php') as $fileName)
{
    require_once $fileName;

    $className = 'MagentoDevBox\\Command\\' . basename($fileName, '.php');
    $commands[] = new $className();
}

$application->addCommands($commands);
$wrapperCommand = new MagentoInstallAll();
$application->add($wrapperCommand);
$wrapperCommand->postConfigure();
$application->run();
