#!/usr/bin/env php
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace MagentoDevBox;

if (file_exists('/var/www/magento2/status.html')) {
    $status = file_get_contents('/var/www/magento2/status.html');
    if (strpos($status, 'IN PROGRESS') !== false) {
        echo $status;
        if (file_exists("/root/unison.log")) {
           passthru("tail /root/unison.log");
        }
        die();
    }
}

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/Command/MagentoInstall.php';

use MagentoDevBox\Command\MagentoInstall;
use Symfony\Component\Console\Application;

$application = new Application();
$commands = [];

foreach (glob(__DIR__ . '/Command/Sub/*.php') as $fileName)
{
    require_once $fileName;

    $className = 'MagentoDevBox\\Command\\Sub\\' . basename($fileName, '.php');
    $commands[] = new $className();
}

$application->addCommands($commands);
$wrapperCommand = new MagentoInstall();
$application->add($wrapperCommand);
$wrapperCommand->postConfigure();
$application->run();
